name: Infrastructure deployment

on:
  workflow_dispatch: ## Manually update infrastructure, hopefully not needed much. 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v3

    - name: Update infrastructure
      run: ./nx build-infra-ci infrastructure
